In [1]:
import numpy
n=numpy.arange(27)

In [6]:
type(n)

numpy.ndarray

In [2]:
n.reshape(3,9)

NameError: name 'n' is not defined

In [2]:
import cv2

In [10]:
im_g=cv2.imread("smallgray.png.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
im_g[0:2,2:3]

array([[104],
       [255]], dtype=uint8)

In [18]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [19]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [26]:
import numpy

In [27]:
ims=numpy.hstack((im_g,im_g))

In [28]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
ims=numpy.vstack((im_g,im_g))

In [30]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [33]:
im=numpy.vsplit(ims,3)

In [34]:
im

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]